-- Tambah kolom tracking aktivitas pengguna di tabel akun
ALTER TABLE akun 
ADD COLUMN IF NOT EXISTS last_login DATETIME NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS last_activity DATETIME NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_online TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ip_address VARCHAR(45) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS user_agent VARCHAR(255) NULL DEFAULT NULL;
